xtrain=read.table("./train/X_train.txt")
ytrain=read.table("./train/y_train.txt")
colnames(ytrain)=c("y")
xtest=read.table("./test/X_test.txt")
ytest=read.table("./test/y_test.txt")
colnames(ytest)=c("y")
ytest[ytest==1]<-"LAYING"
ytest[ytest==3]<-"STANDING"
ytest[ytest==2]<-"SITTING"
ytest[ytest==4]<-"WALKING"
ytest[ytest==5]<-"WALKING_DOWNSTAIRS"
ytest[ytest==6]<-"WALKING_UPSTAIRS"
ytest=as.factor(ytest[,1])
ytrain[ytrain==1]<-"LAYING"
ytrain[ytrain==3]<-"STANDING"
ytrain[ytrain==2]<-"SITTING"
ytrain[ytrain==4]<-"WALKING"
ytrain[ytrain==5]<-"WALKING_DOWNSTAIRS"
ytrain[ytrain==6]<-"WALKING_UPSTAIRS"
ytrain=as.factor(ytrain[,1])
test=cbind(xtest,ytest)
train=cbind(xtrain,ytrain)
subtrain=read.table("./train/subject_train.txt")
subtest=read.table("./test/subject_test.txt")
test$subject=subtest
train$subject=subtrain
colnames(train[,563])="sub"
colnames(test[,563])="sub"
colnames(test)[562]="activity"
colnames(train)[562]="activity"
dataset1=rbind(train,test,row.names=FALSE)
feature=read.table("features.txt")
nm=(feature[,2])
dataset2=dataset1
colnames(dataset2)<-nm
colnames(dataset2)[562]<-"activity"
colnames(dataset2)[563]<-"subject"
df<-dataset2[,grep("mean()",colnames(dataset2))]
df2<-dataset2[,grep("std()",colnames(dataset2))]
df<-cbind(df,df2)
df$Activity=dataset2$activity
df$subject=dataset2$subject
df<-df[1:10299,]
df2<-df[,c(81,80,1:79)]
library(reshape2)
meltdf<-melt(df2,id=c(1,2),measure.vars=c(3:81))
Subdata<-dcast(meltdf,subject+Activity~variable,mean)



